// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAtbf_cTRmf930vR9RmvCK7GbUeUfNq5Y',
    appId: '1:29397982630:web:418cfb2dfca5b21c0e4367',
    messagingSenderId: '29397982630',
    projectId: 'securityawereness',
    authDomain: 'securityawereness.firebaseapp.com',
    storageBucket: 'securityawereness.firebasestorage.app',
    measurementId: 'G-42TSC9RX2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXH6zOE7ah-gFNV5E15oWuX8vMtfUK-qk',
    appId: '1:29397982630:android:eadf42578d0d20860e4367',
    messagingSenderId: '29397982630',
    projectId: 'securityawereness',
    storageBucket: 'securityawereness.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0ukeqxbcjA0yVEsdes_olSTlrCTTFGck',
    appId: '1:29397982630:ios:543e2bb6c92360f80e4367',
    messagingSenderId: '29397982630',
    projectId: 'securityawereness',
    storageBucket: 'securityawereness.firebasestorage.app',
    iosClientId: '29397982630-hphqrl0ef40m1pg5gqig80nmj7lj5aqt.apps.googleusercontent.com',
    iosBundleId: 'com.example.securityAwarenessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0ukeqxbcjA0yVEsdes_olSTlrCTTFGck',
    appId: '1:29397982630:ios:543e2bb6c92360f80e4367',
    messagingSenderId: '29397982630',
    projectId: 'securityawereness',
    storageBucket: 'securityawereness.firebasestorage.app',
    iosClientId: '29397982630-hphqrl0ef40m1pg5gqig80nmj7lj5aqt.apps.googleusercontent.com',
    iosBundleId: 'com.example.securityAwarenessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAtbf_cTRmf930vR9RmvCK7GbUeUfNq5Y',
    appId: '1:29397982630:web:9e22e3ec34f017a00e4367',
    messagingSenderId: '29397982630',
    projectId: 'securityawereness',
    authDomain: 'securityawereness.firebaseapp.com',
    storageBucket: 'securityawereness.firebasestorage.app',
    measurementId: 'G-D5RKWKMN9Z',
  );
}
